runtime: php55

handlers:

- url: /img/(.*\.(gif|png|jpg))
  static_files: img/\1
  upload: img/(.*\.(gif|png|jpg))

- url: /css/(.*\.(css))
  static_files: css/\1
  upload: css/(.*\.(css))

- url: /.*
  script: index.html
